export const careersData = [
  {
    title: "Software Engineer",
    heading: "Work on cutting-edge projects and technologies.",
    location: "Bangalore",
    experience: "5+ years",
    requirements: [
      "Strong knowledge of JavaScript (ES6+), HTML, CSS, and related web technologies",
      "Proficiency in React, Angular, or Vue.js",
      "Experience with Node.js or other backend technologies",
      "Expertise in designing and consuming RESTful services",
      "Experience with MySQL, PostgreSQL, or NoSQL databases like MongoDB",
      "Proficient with Git and code reviews",
      "Familiar with Jira or similar tools",
      "Experience with unit testing, integration testing, debugging, and logging",
      "Knowledge of build tools and task runners like Webpack, Gulp, or npm scripts",
    ],
    qualifications: [
      "Server-Side Rendering: Experience with Next.js or Nuxt.js",
      "Caching: Understanding of caching strategies and tools like Redis or Memcached",
      "Message Brokers: Experience with RabbitMQ or Kafka",
      "Cloud Platforms: Knowledge of AWS or other cloud platforms",
    ],
  },
  {
    title: "Product Manager",
    heading: "Lead product development and strategy",
    location: "Bangalore",
    experience: "5+ years",
    requirements: [
      "Lead the development and execution of product strategies aligned with business goals.",
      "Oversee the entire product lifecycle, from concept through launch and beyond.",
      "Collaborate with cross-functional teams to deliver innovative solutions.",
      "Conduct market research, competitive analysis, and customer feedback.",
      "Prioritize product roadmap and manage the product backlog.",
      "Define and track key product metrics to evaluate success.",
      "Ensure timely delivery of product releases.",
    ],
    qualifications: [
      "Proven experience in product management or similar roles.",
      "Strong understanding of software development and product lifecycle processes.",
      "Excellent communication and leadership skills.",
      "Data-driven approach to problem-solving.",
      "Ability to manage multiple projects in a fast-paced environment.",
    ],
  },
  {
    title: "Marketing Specialist",
    heading: "Drive global marketing campaigns and initiatives.",
    location: "Bangalore",
    experience: "3+ years",
    requirements: [
      "Develop and execute global marketing campaigns to promote products and services.",
      "Drive brand awareness, lead generation, and customer engagement.",
      "Collaborate with product, sales, and design teams to create marketing materials.",
      "Manage social media, email marketing, content marketing, and SEO/SEM initiatives.",
      "Analyze campaign performance and provide insights for optimization.",
      "Conduct market research to identify trends and customer needs.",
      "Manage external vendors and agencies to support marketing objectives.",
    ],
    qualifications: [
      "Proven experience in marketing, with a focus on digital marketing.",
      "Strong analytical skills to track marketing effectiveness.",
      "Familiarity with marketing tools and platforms like Google Analytics, SEO tools, etc.",
      "Excellent communication skills and creativity in content creation.",
      "Ability to work independently and manage multiple projects.",
    ],
  },
];
